
//asval, Mk17 and SCAR-H arguable

private _categoryOverrideTable = [
["rhs_weap_vss", ["SniperRifles","Weapons"]],
["rhs_weap_vss_grip", ["SniperRifles","Weapons"]],
["rhs_weap_vss_npz", ["SniperRifles","Weapons"]],
["rhs_weap_vss_grip_npz", ["SniperRifles","Weapons"]],
["rhs_weap_svdp", ["SniperRifles","Weapons"]],
["rhs_weap_svdp_npz", ["SniperRifles","Weapons"]],
["rhs_weap_svdp_wd", ["SniperRifles","Weapons"]],
["rhs_weap_svdp_wd_npz", ["SniperRifles","Weapons"]],
["rhs_weap_svds", ["SniperRifles","Weapons"]],
["rhs_weap_svds_npz", ["SniperRifles","Weapons"]],
["rhs_weap_t5000", ["SniperRifles","Weapons"]],
["rhs_weap_pp2000", ["SMGs","Weapons"]],
["rhs_weap_XM2010", ["SniperRifles","Weapons"]],
["rhs_weap_XM2010_d", ["SniperRifles","Weapons"]],
["rhs_weap_XM2010_wd", ["SniperRifles","Weapons"]],
["rhs_weap_XM2010_sa", ["SniperRifles","Weapons"]],
["rhs_weap_m24sws", ["SniperRifles","Weapons"]],
["rhs_weap_m24sws_d", ["SniperRifles","Weapons"]],
["rhs_weap_m24sws_wd", ["SniperRifles","Weapons"]],
["rhs_weap_m40a5", ["SniperRifles","Weapons"]],
["rhs_weap_m40a5_d", ["SniperRifles","Weapons"]],
["rhs_weap_m40a5_wd", ["SniperRifles","Weapons"]],
["rhs_weap_M590_5RD", ["Shotguns","Weapons"]],
["rhs_weap_M590_8RD", ["Shotguns","Weapons"]],
["rhs_weap_kar98k", ["SniperRifles","Weapons"]],
["rhs_weap_m38", ["SniperRifles","Weapons"]],
["rhs_weap_m38_rail", ["SniperRifles","Weapons"]],
["rhs_weap_mosin_sbr", ["SniperRifles","Weapons"]],
["rhs_weap_mg42", ["MachineGuns","Weapons"]],
["rhs_weap_Izh18", ["Shotguns","Weapons"]],

["rhs_weap_M320", ["GrenadeLaunchers","Weapons"]],
["rhs_weap_m27iar", ["MachineGuns","Weapons"]],
["rhs_weap_m27iar_grip", ["MachineGuns","Weapons"]],
["rhs_weap_m32", ["GrenadeLaunchers","Weapons"]],
["rhs_weap_m79", ["GrenadeLaunchers","Weapons"]],

["UK3CB_Enfield", ["SniperRifles","Weapons"]],
["UK3CB_Enfield_rail", ["SniperRifles","Weapons"]],
["UK3CB_M14DMR", ["SniperRifles","Weapons"]],
["UK3CB_M21", ["SniperRifles","Weapons"]],
["UK3CB_SVD_OLD", ["SniperRifles","Weapons"]],
["UK3CB_M16A1_LSW", ["MachineGuns","Weapons"]],

["UK3CB_BAF_Javelin_Launcher", ["MissileLaunchers","Weapons","AT"]],
["UK3CB_BAF_Javelin_CLU", ["Binoculars","Items"]],
["UK3CB_BAF_Javelin_Slung_Tube", ["MissileLaunchers","Weapons","AT"]],
["UK3CB_M79", ["GrenadeLaunchers","Weapons"]],
["UK3CB_BAF_AT4_CS_AT_Launcher", ["RocketLaunchers","Weapons","AT"]],
["UK3CB_BAF_AT4_CS_AP_Launcher", ["RocketLaunchers","Weapons","AT"]],

["launch_NLAW_F", ["MissileLaunchers","Weapons","AT"]],
["hgun_PDW2000_F", ["SMGs","Weapons"]],

["UK3CB_BAF_L86A2", ["MachineGuns","Weapons"]],
["UK3CB_BAF_L86A3", ["MachineGuns","Weapons"]],

["UK3CB_BAF_Tripod", ["StaticWeaponParts","Items"]],
["UK3CB_BAF_L16_Tripod", ["StaticWeaponParts","Items"]],
["UK3CB_BAF_L111A1", ["StaticWeaponParts","Items"]],
["UK3CB_BAF_L134A1", ["StaticWeaponParts","Items"]],
["UK3CB_BAF_L16", ["StaticWeaponParts","Items"]],
["UK3CB_BAF_M6", ["StaticWeaponParts","Items"]],

["UK3CB_M14_Rail", ["SniperRifles","Weapons"]],
["UK3CB_M21_Bipod_Railed", ["SniperRifles","Weapons"]],
["UK3CB_M14DMR_Railed", ["SniperRifles","Weapons"]],

["ace_csw_m3CarryTripod", ["StaticWeaponParts","Items"]],
["ace_csw_m3CarryTripodLow", ["StaticWeaponParts","Items"]],
["ace_csw_kordCarryTripod", ["StaticWeaponParts","Items"]],
["ace_csw_kordCarryTripodLow", ["StaticWeaponParts","Items"]],
["ace_csw_m220CarryTripod", ["StaticWeaponParts","Items"]],
["ace_csw_spg9CarryTripod", ["StaticWeaponParts","Items"]],
["ace_csw_sag30CarryTripod", ["StaticWeaponParts","Items"]],
["ace_csw_carryMortarBaseplate", ["StaticWeaponParts","Items"]],
["ace_csw_staticATCarry", ["StaticWeaponParts","Items"]],
["ace_csw_staticAACarry", ["StaticWeaponParts","Items"]],
["ace_csw_staticHMGCarry", ["StaticWeaponParts","Items"]],
["ace_csw_staticGMGCarry", ["StaticWeaponParts","Items"]],
["ace_csw_staticMortarCarry", ["StaticWeaponParts","Items"]],
["ace_csw_staticM2ShieldCarry", ["StaticWeaponParts","Items"]],

["ace_compat_rhs_afrf3_2b14_carry", ["StaticWeaponParts","Items"]],
["ace_compat_rhs_afrf3_nsv_carry" , ["StaticWeaponParts","Items"]],
["ace_compat_rhs_afrf3_kord_carry" , ["StaticWeaponParts","Items"]],
["ace_compat_rhs_afrf3_ags30_carry" , ["StaticWeaponParts","Items"]],
["ace_compat_rhs_afrf3_spg9_carry" , ["StaticWeaponParts","Items"]],
["ace_compat_rhs_afrf3_spg9m_carry" , ["StaticWeaponParts","Items"]],
["ace_compat_rhs_afrf3_metis_carry" , ["StaticWeaponParts","Items"]],
["ace_compat_rhs_afrf3_kornet_carry" , ["StaticWeaponParts","Items"]],
["ace_compat_rhs_usf3_m252_carry" , ["StaticWeaponParts","Items"]],
["ace_compat_rhs_usf3_m2_carry" , ["StaticWeaponParts","Items"]],
["ace_compat_rhs_usf3_mk19_carry" , ["StaticWeaponParts","Items"]],
["ace_compat_rhs_usf3_tow_carry" , ["StaticWeaponParts","Items"]],
["ace_compat_rhs_gref3_dshkm_carry" , ["StaticWeaponParts","Items"]],

["ace_dragon_super", ["MissileLaunchers","Weapons","AT"]],
["ace_dragon_sight", ["Binoculars","Items"]],

["ACE_Kestrel4500", ["Gadgets","Items"]],
["ACE_ATragMX", ["Gadgets","Items"]],
["ACE_HuntIR_monitor", ["Gadgets","Items"]],
["ACE_microDAGR", ["Gadgets","Items"]],
["ACE_DAGR", ["Gadgets","Items"]],

["LIB_PTRD", ["Unknown", "Weapons"]],
["LIB_M2_Flamethrower", ["Unknown", "Weapons"]],			// don't want these two being chosen randomly by AIs
["LIB_Bagpipes", ["Unknown","Weapons"]],					// wat
["ACE_SatchelCharge_Remote_Mag_Throwable", ["Unknown", "Explosives", "Items"]],
["ACE_DemoCharge_Remote_Mag_Throwable", ["Unknown", "Explosives", "Items"]],
//Flashlights
["vn_mx991", ["Unknown","Weapons"]],
["vn_mx991_red", ["Unknown","Weapons"]],
["vn_fkb1_red", ["Unknown","Weapons"]],
["vn_fkb1", ["Unknown","Weapons"]],
["ACE_Flashlight_Maglite_ML300L", ["Unknown","Weapons"]],

["vn_default_helmetbase_09", ["Unknown","Headgear"]],	//Goat Hat
["vn_m1897", ["Shotguns","Weapons"]],
["vn_izh54", ["Shotguns","Weapons"]],
["vn_izh54_shorty", ["Shotguns","Weapons"]],
["vn_pps52", ["SMGs","Weapons"]],
["vn_pps43", ["SMGs","Weapons"]],
["vn_mc10", ["SMGs","Weapons"]],
["vn_ppsh41", ["SMGs","Weapons"]],
["vn_k50m", ["SMGs","Weapons"]],
["vn_mat49", ["SMGs","Weapons"]],
["vn_mat49_f", ["SMGs","Weapons"]],
["vn_mat49_vc", ["SMGs","Weapons"]],
["vn_m3a1", ["SMGs","Weapons"]],
["vn_sten", ["SMGs","Weapons"]],
["vn_m79", ["GrenadeLaunchers","Weapons"]],
["vn_sa7b", ["MissileLaunchers","Weapons"]],
["vn_sa7", ["MissileLaunchers","Weapons"]],
["vn_m4956_gl", ["GrenadeLaunchers","Weapons"]],
["vn_m2carbine_gl", ["GrenadeLaunchers","Weapons"]],
["vn_m1carbine_gl", ["GrenadeLaunchers","Weapons"]],
["vn_sks_gl", ["GrenadeLaunchers","Weapons"]],
["vn_type56", ["Rifles","Weapons"]],

//ACRE Radios
//Using Gadgets instead of Radios to prevent future issues as they don't use the Radio Slot
["ACRE_PRC148", ["Gadgets","items"]],
["ACRE_PRC152", ["Gadgets","items"]],
["ACRE_PRC343", ["Gadgets","items"]],
["ACRE_PRC77", ["Gadgets","items"]],
["ACRE_SEM52SL", ["Gadgets","items"]],
["ACRE_SEM70", ["Gadgets","items"]],
["ACRE_VHF30108SPIKE", ["Gadgets","items"]],
["ACRE_VHF30108", ["Gadgets","items"]],
["ACRE_VHF30108MAST", ["Gadgets","items"]],
["ACRE_PRC117F", ["Gadgets","items"]],

["LIB_M2_Tripod", ["StaticWeaponParts","Items"]],
["LIB_Laffete_Tripod", ["StaticWeaponParts","Items"]],
["LIB_BM37_Tripod", ["StaticWeaponParts","Items"]],
["LIB_BM37_Barrel", ["StaticWeaponParts","Items"]],
["LIB_GrWr34_Tripod", ["StaticWeaponParts","Items"]],
["LIB_GrWr34_Tripod_g", ["StaticWeaponParts","Items"]],
["LIB_GrWr34_Barrel", ["StaticWeaponParts","Items"]],
["LIB_GrWr34_Barrel_g", ["StaticWeaponParts","Items"]],
["LIB_M2_60_Tripod", ["StaticWeaponParts","Items"]],
["LIB_M2_60_Barrel", ["StaticWeaponParts","Items"]]   ];

//Create a local namespace. Should only run on the server.
categoryOverrides = false call A3A_fnc_createNamespace;
{
	categoryOverrides setVariable [_x select 0, _x select 1];
} forEach _categoryOverrideTable;
