/*
Maintainer: DoomMetal
    Contains defines for texture paths.

    Examples:
    Getting textures from arma: "\a3\3DEN\Data\Controls\ctrlDefault\arrowEmpty_ca.paa)
    Getting textures from mission: A3A_GUI_QTEXTURE_PATH_OF(icon_undercover.paa)

*/

// Defines for texture paths
// Arma paths example: "\a3\3DEN\Data\Controls\ctrlDefault\arrowEmpty_ca.paa)
// Mission paths example: A3A_GUI_QTEXTURE_PATH_OF(icon_undercover.paa)

#ifndef INCLUDED_DEFINES_HPP
    #include "defines.hpp"
#endif

#define A3A_ArrowEmpty_1L           A3A_GUI_QTEXTURE_PATH_OF(arrowEmpty_1L.paa)
#define A3A_ArrowEmpty_1R           A3A_GUI_QTEXTURE_PATH_OF(arrowEmpty_1R.paa)
#define A3A_ArrowEmpty_2L           A3A_GUI_QTEXTURE_PATH_OF(arrowEmpty_2L.paa)
#define A3A_ArrowEmpty_2R           A3A_GUI_QTEXTURE_PATH_OF(arrowEmpty_2R.paa)
#define A3A_ArrowEmpty_3L           A3A_GUI_QTEXTURE_PATH_OF(arrowEmpty_3L.paa)
#define A3A_ArrowEmpty_3R           A3A_GUI_QTEXTURE_PATH_OF(arrowEmpty_3R.paa)
#define A3A_ArrowFull_1L            A3A_GUI_QTEXTURE_PATH_OF(arrowFull_1L.paa)
#define A3A_ArrowFull_1R            A3A_GUI_QTEXTURE_PATH_OF(arrowFull_1R.paa)
#define A3A_ArrowFull_2L            A3A_GUI_QTEXTURE_PATH_OF(arrowFull_2L.paa)
#define A3A_ArrowFull_2R            A3A_GUI_QTEXTURE_PATH_OF(arrowFull_2R.paa)
#define A3A_ArrowFull_3L            A3A_GUI_QTEXTURE_PATH_OF(arrowFull_3L.paa)
#define A3A_ArrowFull_3R            A3A_GUI_QTEXTURE_PATH_OF(arrowFull_3R.paa)
#define A3A_Icon_AA_Truck           A3A_GUI_QTEXTURE_PATH_OF(icon_aa_truck.paa)
#define A3A_Icon_Add_Garrison       A3A_GUI_QTEXTURE_PATH_OF(icon_add_garrison.paa)
#define A3A_Icon_AI_Management      A3A_GUI_QTEXTURE_PATH_OF(icon_ai_management.paa)
#define A3A_Icon_Assassination      A3A_GUI_QTEXTURE_PATH_OF(icon_assassination.paa)
#define A3A_Icon_AT                 A3A_GUI_QTEXTURE_PATH_OF(icon_at.paa)
#define A3A_Icon_AT_Car             A3A_GUI_QTEXTURE_PATH_OF(icon_at_car.paa)
#define A3A_Icon_AT_Team            A3A_GUI_QTEXTURE_PATH_OF(icon_at_team.paa)
#define A3A_Icon_Autorifleman       A3A_GUI_QTEXTURE_PATH_OF(icon_autorifleman.paa)
#define A3A_Icon_Bomb_Specialist    A3A_GUI_QTEXTURE_PATH_OF(icon_bomb_specialist.paa)
#define A3A_Icon_Cargo              A3A_GUI_QTEXTURE_PATH_OF(icon_cargo.paa)
#define A3A_Icon_Carpet_Bombing     A3A_GUI_QTEXTURE_PATH_OF(icon_carpet_bombing.paa)
#define A3A_Icon_Commander          A3A_GUI_QTEXTURE_PATH_OF(icon_commander.paa)
#define A3A_Icon_Conquest           A3A_GUI_QTEXTURE_PATH_OF(icon_conquest.paa)
#define A3A_Icon_Convoy_Ambush      A3A_GUI_QTEXTURE_PATH_OF(icon_convoy_ambush.paa)
#define A3A_Icon_Destroy            A3A_GUI_QTEXTURE_PATH_OF(icon_destroy.paa)
#define A3A_Icon_Dismiss            A3A_GUI_QTEXTURE_PATH_OF(icon_dismiss.paa)
#define A3A_Icon_Driver             A3A_GUI_QTEXTURE_PATH_OF(icon_driver.paa)
#define A3A_Icon_FastTravel         A3A_GUI_QTEXTURE_PATH_OF(icon_fasttravel.paa)
#define A3A_Icon_FFV                A3A_GUI_QTEXTURE_PATH_OF(icon_ffv.paa)
#define A3A_Icon_Garrison           A3A_GUI_QTEXTURE_PATH_OF(icon_garrison.paa)
#define A3A_Icon_Grenadier          A3A_GUI_QTEXTURE_PATH_OF(icon_grenadier.paa)
#define A3A_Icon_Gunner             A3A_GUI_QTEXTURE_PATH_OF(icon_gunner.paa)
#define A3A_Icon_Has_AA             A3A_GUI_QTEXTURE_PATH_OF(icon_has_aa.paa)
#define A3A_Icon_Has_AT             A3A_GUI_QTEXTURE_PATH_OF(icon_has_at.paa)
#define A3A_Icon_Has_Mortar         A3A_GUI_QTEXTURE_PATH_OF(icon_has_mortar.paa)
#define A3A_Icon_Has_Static         A3A_GUI_QTEXTURE_PATH_OF(icon_has_static.paa)
#define A3A_Icon_HE_Bombs           A3A_GUI_QTEXTURE_PATH_OF(icon_he_bombs.paa)
#define A3A_Icon_Hide               A3A_GUI_QTEXTURE_PATH_OF(icon_hide.paa)
#define A3A_Icon_HideVic            A3A_GUI_QTEXTURE_PATH_OF(icon_hidevic.paa)
#define A3A_Icon_Inf_Squad          A3A_GUI_QTEXTURE_PATH_OF(icon_inf_squad.paa)
#define A3A_Icon_Inf_Team           A3A_GUI_QTEXTURE_PATH_OF(icon_inf_team.paa)
#define A3A_Icon_Logistics          A3A_GUI_QTEXTURE_PATH_OF(icon_logistics.paa)
#define A3A_Icon_Medic              A3A_GUI_QTEXTURE_PATH_OF(icon_medic.paa)
#define A3A_Icon_MG_Team            A3A_GUI_QTEXTURE_PATH_OF(icon_mg_team.paa)
#define A3A_Icon_Minefield          A3A_GUI_QTEXTURE_PATH_OF(icon_minefield.paa)
#define A3A_Icon_Mortar_Team        A3A_GUI_QTEXTURE_PATH_OF(icon_mortar_team.paa)
#define A3A_Icon_Move_HQ            A3A_GUI_QTEXTURE_PATH_OF(icon_move_hq.paa)
#define A3A_Icon_Napalm_Bomb        A3A_GUI_QTEXTURE_PATH_OF(icon_napalm_bomb.paa)
#define A3A_Icon_None               A3A_GUI_QTEXTURE_PATH_OF(icon_none.paa)
#define A3A_Icon_Pilot              A3A_GUI_QTEXTURE_PATH_OF(icon_pilot.paa)
#define A3A_Icon_Rescue             A3A_GUI_QTEXTURE_PATH_OF(icon_rescue.paa)
#define A3A_Icon_Rifleman           A3A_GUI_QTEXTURE_PATH_OF(icon_rifleman.paa)
#define A3A_Icon_Sniper             A3A_GUI_QTEXTURE_PATH_OF(icon_sniper.paa)
#define A3A_Icon_Sniper_Team        A3A_GUI_QTEXTURE_PATH_OF(icon_sniper_team.paa)
#define A3A_Icon_Train_Troops       A3A_GUI_QTEXTURE_PATH_OF(icon_train_troops.paa)
#define A3A_Icon_Undercover         A3A_GUI_QTEXTURE_PATH_OF(icon_undercover.paa)
#define A3A_Icon_AP_Minefield       A3A_GUI_QTEXTURE_PATH_OF(icon_ap_minefield.paa)
#define A3A_Icon_AT_Minefield       A3A_GUI_QTEXTURE_PATH_OF(icon_at_minefield.paa)
#define A3A_Icon_Town               A3A_GUI_QTEXTURE_PATH_OF(icon_town.paa)
#define A3A_Icon_Outpost            A3A_GUI_QTEXTURE_PATH_OF(icon_outpost.paa)
#define A3A_Icon_Airbase            A3A_GUI_QTEXTURE_PATH_OF(icon_airbase.paa)
#define A3A_Icon_Factory            A3A_GUI_QTEXTURE_PATH_OF(icon_factory.paa)
#define A3A_Icon_Resource           A3A_GUI_QTEXTURE_PATH_OF(icon_resource.paa)
#define A3A_Icon_Seaport            A3A_GUI_QTEXTURE_PATH_OF(icon_seaport.paa)
#define A3A_Icon_Clear_Trees        A3A_GUI_QTEXTURE_PATH_OF(icon_clear_trees.paa)
#define A3A_Icon_Support            A3A_GUI_QTEXTURE_PATH_OF(icon_support.paa)

// New map icons
#define A3A_Icon_Map_Blank          A3A_GUI_QTEXTURE_PATH_OF(icon_map_blank.paa)
#define A3A_Icon_Map_City           A3A_GUI_QTEXTURE_PATH_OF(icon_map_city.paa)
#define A3A_Icon_Map_Factory        A3A_GUI_QTEXTURE_PATH_OF(icon_map_factory.paa)
#define A3A_Icon_Map_Resource       A3A_GUI_QTEXTURE_PATH_OF(icon_map_resource.paa)
#define A3A_Icon_Map_Airport        A3A_GUI_QTEXTURE_PATH_OF(icon_map_airport.paa)
#define A3A_Icon_Map_Seaport        A3A_GUI_QTEXTURE_PATH_OF(icon_map_seaport.paa)
#define A3A_Icon_Map_Outpost        A3A_GUI_QTEXTURE_PATH_OF(icon_map_outpost.paa)
#define A3A_Icon_Map_Roadblock      A3A_GUI_QTEXTURE_PATH_OF(icon_map_roadblock.paa)
#define A3A_Icon_Map_Watchpost      A3A_GUI_QTEXTURE_PATH_OF(icon_map_watchpost.paa)
#define A3A_Icon_Map_HQ             A3A_GUI_QTEXTURE_PATH_OF(icon_map_hq.paa)


// From Arma
#define A3A_Icon_Construct          "\a3\ui_f\data\igui\cfg\cursors\iconRepairVehicle_ca.paa"
#define A3A_Icon_Close              "\A3\ui_f\data\GUI\RscCommon\RscButtonSearch\search_end_ca.paa"
#define A3A_Icon_Back               "\A3\ui_f\data\GUI\RscCommon\RscHTML\arrow_left_ca.paa"
#define A3A_Icon_Remotecontrol      "\a3\modules_f_curator\data\portraitremotecontrol_ca.paa"
#define A3A_Icon_Rearm              "\A3\Ui_f\data\IGUI\Cfg\Actions\reammo_ca.paa"
#define A3A_Icon_Heal               "\A3\ui_f\data\igui\cfg\actions\heal_ca.paa"
#define A3A_Icon_Warning            "\A3\Ui_f\data\Map\Markers\Military\warning_CA.paa"
#define A3A_Icon_GroupUnitCount     "\A3\ui_f\data\igui\cfg\simpleTasks\types\meet_ca.paa"
#define A3A_Select_Marker           "\A3\ui_f\data\IGUI\Cfg\Cursors\selectOver_ca.paa"

// Commander picture
#define A3A_Icon_PlayerCommander    "\A3\Ui_f\data\GUI\Cfg\Ranks\colonel_gs.paa"
#define A3A_Icon_PlayerEligible     "\A3\Ui_f\data\GUI\Cfg\Ranks\colonel_gs.paa"
#define A3A_Icon_PlayerIneligible   A3A_GUI_QTEXTURE_PATH_OF(icon_ineligible.paa)

// Place Holders
#define A3A_PlaceHolder_NoVehiclePreview   A3A_GUI_QTEXTURE_PATH_OF(placeholder_no_vehicle_preview.paa)
