class mapInfo {
    #include "Antistasi_Altis.Altis\mapInfo.hpp"
    #include "Antistasi_cam_lao_nam.cam_lao_nam\mapInfo.hpp"
    #include "Antistasi_chernarus_summer.chernarus_summer\mapInfo.hpp"
    #include "Antistasi_chernarus_winter.chernarus_winter\mapInfo.hpp"
    #include "Antistasi_Enoch.Enoch\mapInfo.hpp"
    #include "Antistasi_Kunduz.Kunduz\mapInfo.hpp"
    #include "Antistasi_Malden.Malden\mapInfo.hpp"
    #include "Antistasi_sara.sara\mapInfo.hpp"
    #include "Antistasi_Stratis.Stratis\mapInfo.hpp"
    #include "Antistasi_takistan.takistan\mapInfo.hpp"
    #include "Antistasi_Tanoa.Tanoa\mapInfo.hpp"
    #include "Antistasi_tem_anizay.tem_anizay\mapInfo.hpp"
    #include "Antistasi_Tembelan.Tembelan\mapInfo.hpp"
    #include "Antistasi_vt7.vt7\mapInfo.hpp"
};
