#include "..\..\..\..\..\script_component.hpp"

UPSMON_DOPATROLSRCH = compile preProcessFileLineNumbers QPATHTOFOLDER(Scripts\UPSMON\MODULES\ORDERS\UPSMON_PATROLSRCH\fnc\UPSMON_DOPATROLSRCH.sqf);
UPSMON_SrchPtrlFlankPos = compile preProcessFileLineNumbers QPATHTOFOLDER(Scripts\UPSMON\MODULES\ORDERS\UPSMON_PATROLSRCH\fnc\UPSMON_SrchPtrlFlankPos.sqf);
UPSMON_GETINPATROLSRCH = compile preProcessFileLineNumbers QPATHTOFOLDER(Scripts\UPSMON\MODULES\ORDERS\UPSMON_PATROLSRCH\fnc\UPSMON_GETINPATROLSRCH.sqf);
