[
	[
		"rhs_weap_ak105",
		"rhs_acc_pgs64",
		"rhs_acc_perst1ik",
		"",
		["rhs_30Rnd_545x39_7N22_AK",30],
		[],
		""
	],
	[],
	[],
	[
		"rhs_uniform_gorka_r_g",
		[] + _basicMedicalSupplies + _basicMiscItems
	],
	[
		"rhs_6b23_6sh116_od",
		[
			["rhs_1PN138",1],
			["rhs_30Rnd_545x39_7N22_AK",4,30],
			["rhs_mag_rgo",1,1],
			["rhs_mag_rgn",1,1],
			["rhs_mag_rdg2_white",2,1]]],
	[
		"rhs_medic_bag",
		[] + _medicSupplies
	],
	"rhs_altyn_novisor_ess_bala",
	"",
	[],
	[
		"ItemMap",
		"",
		["tf_fadak_1"] call _fnc_tfarRadio,
		"ItemCompass",
		"ItemWatch",
		""
	]
];
