private _loadout_rhs_afrf_AT2 =[
	["rhs_weap_ak105",
		"rhs_acc_pgs64",
		"rhs_acc_perst1ik",
		"",
		["rhs_30Rnd_545x39_7N22_AK",30],
		[],
		""
	],
	[],
	[],
	[
		"rhs_uniform_gorka_r_g",
		[
			["ACE_CableTie",3],
			["ACE_EarPlugs",1],
			["ACE_salineIV_500",1],
			["ACE_tourniquet",1],
			["ACE_Flashlight_XL50",1],
			["ACE_epinephrine",2],
			["ACE_morphine",2],
			["ACE_packingBandage",5],
			["ACE_quikclot",3],
			["ACE_elasticBandage",3]]],
	[
		"rhs_6b23_6sh116_od",
		[
			["rhs_1PN138",1],
			["rhs_30Rnd_545x39_7N22_AK",4,30],
			["rhs_mag_rgn",1,1],
			["rhs_mag_rdg2_white",1,1],
			["rhs_mag_rgo",1,1]]],
	[
		"RHS_Kornet_Tripod_Bag",
		[]
	],
	"rhs_altyn",
	"rhs_balaclava",
	[
		"Binocular",
		"",
		"",
		"",
		[],
		[],
		""
	],
	[
		"ItemMap",
		"",
		"tf_fadak_1",
		"ItemCompass",
		"ItemWatch",
		""
	]
];
